"""Provenance tracking for Induction Motor Condition Monitoring (IMCM) outputs.

This project is a student engineering submission, not a commercial digital twin.
Every dataset it produces -- a simulated run, a literature-derived parameter set,
or (only if real measurements exist) an experimental record -- must carry an
explicit provenance record so its origin can never be misread.

The three permitted dataset labels are deliberately narrow:

    simulated
        Produced entirely by the reduced-order model in this repository.
        No measured data involved.

    literature-example
        Parameter values taken from published examples / textbooks. These are
        development starting values, NOT identified data for any physical motor.

    experimental
        Reserved for real measured data with documented provenance. Must not be
        used for anything generated by this repository.

This module is intentionally self-contained and uses only the Python standard
library so it can be imported without pulling in the scientific stack.
"""

from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence, Union

__all__ = [
    "ALLOWED_DATASET_LABELS",
    "ProvenanceError",
    "ProvenanceRecord",
    "utc_now_iso",
    "detect_git_commit",
    "write_manifest",
    "read_manifest",
]


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: The only dataset labels this project is allowed to emit.
ALLOWED_DATASET_LABELS: frozenset[str] = frozenset(
    {"simulated", "literature-example", "experimental"}
)

#: Field names that every provenance record must define.
_REQUIRED_FIELDS: tuple[str, ...] = (
    "dataset_label",
    "parameter_hash",
    "parameter_source",
    "solver_settings",
    "initial_condition",
    "git_commit",
    "timestamp",
    "output_files",
)

#: Optional field linking a manifest back to its run config. It is not in
#: ``_REQUIRED_FIELDS`` so that manifests written before run configs existed
#: remain readable; new manifests always carry it.
_OPTIONAL_FIELDS: tuple[str, ...] = ("run_config",)


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class ProvenanceError(ValueError):
    """Raised when a provenance record is malformed or mislabelled."""


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def utc_now_iso() -> str:
    """Return the current UTC time as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


def detect_git_commit(fallback: str = "unknown") -> str:
    """Best-effort lookup of the current git commit hash.

    Returns ``fallback`` if git is unavailable or the call fails, so that a
    provenance record can always be produced even outside a checkout.
    """
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return fallback
    commit = completed.stdout.strip()
    return commit or fallback


def _validate_dataset_label(label: object) -> str:
    """Normalise and validate a dataset label."""
    if not isinstance(label, str):
        raise ProvenanceError(
            f"dataset_label must be a string, got {type(label).__name__}"
        )
    normalised = label.strip().lower()
    if not normalised:
        raise ProvenanceError("dataset_label must not be empty")
    if normalised not in ALLOWED_DATASET_LABELS:
        allowed = ", ".join(sorted(ALLOWED_DATASET_LABELS))
        raise ProvenanceError(
            f"invalid dataset_label {label!r}; allowed labels are: {allowed}"
        )
    return normalised


def _require_text(name: str, value: object) -> str:
    """Validate that ``value`` is a non-empty string and return it stripped."""
    if not isinstance(value, str):
        raise ProvenanceError(f"{name} must be a string, got {type(value).__name__}")
    stripped = value.strip()
    if not stripped:
        raise ProvenanceError(f"{name} must be a non-empty string")
    return stripped


def _require_mapping(name: str, value: object) -> dict[str, Any]:
    """Validate that ``value`` is a mapping and return a plain dict copy."""
    if not isinstance(value, Mapping):
        raise ProvenanceError(
            f"{name} must be a mapping (e.g. dict), got {type(value).__name__}"
        )
    return dict(value)


def _validate_timestamp(value: object) -> str:
    """Validate that ``value`` is an ISO-8601 timestamp string."""
    text = _require_text("timestamp", value)
    candidate = text[:-1] + "+00:00" if text.endswith("Z") else text
    try:
        datetime.fromisoformat(candidate)
    except ValueError as exc:
        raise ProvenanceError(
            f"timestamp must be an ISO-8601 datetime, got {value!r}"
        ) from exc
    return text


def _normalise_output_files(files: object) -> tuple[str, ...]:
    """Validate and freeze the list of output file paths/names."""
    if isinstance(files, (str, bytes)):
        raise ProvenanceError(
            "output_files must be a sequence of strings, not a single string"
        )
    try:
        items = list(files)  # type: ignore[arg-type]
    except TypeError as exc:
        raise ProvenanceError("output_files must be an iterable of strings") from exc

    normalised: list[str] = []
    for item in items:
        if not isinstance(item, str):
            raise ProvenanceError(
                "every entry in output_files must be a string, "
                f"got {type(item).__name__}"
            )
        stripped = item.strip()
        if not stripped:
            raise ProvenanceError("every entry in output_files must be non-empty")
        normalised.append(stripped)
    return tuple(normalised)


def _jsonable(value: Any) -> Any:
    """Recursively convert mappings/sequences into plain JSON-safe values."""
    if isinstance(value, Mapping):
        return {str(key): _jsonable(val) for key, val in value.items()}
    if isinstance(value, (str, bytes)):
        return value.decode("utf-8") if isinstance(value, bytes) else value
    if isinstance(value, Sequence):
        return [_jsonable(item) for item in value]
    return value


def _coerce_record(record: object) -> "ProvenanceRecord":
    """Accept either a ProvenanceRecord or a raw mapping."""
    if isinstance(record, ProvenanceRecord):
        return record
    if isinstance(record, Mapping):
        return ProvenanceRecord.from_dict(record)
    raise TypeError(
        "record must be a ProvenanceRecord or a mapping, "
        f"got {type(record).__name__}"
    )


# ---------------------------------------------------------------------------
# Record
# ---------------------------------------------------------------------------


@dataclass
class ProvenanceRecord:
    """A self-describing account of how one dataset was produced.

    Parameters
    ----------
    dataset_label:
        One of :data:`ALLOWED_DATASET_LABELS`. Validated on construction.
    parameter_hash:
        Digest (e.g. SHA-256) of the parameter set used, so runs can be traced
        back to exact inputs.
    parameter_source:
        Human-readable description of where the parameters came from. For the
        default machine this should state that it is a literature example.
    solver_settings:
        Mapping of integrator configuration (method, tolerances, max_step,
        time span, etc.).
    initial_condition:
        Mapping describing the initial state (e.g. fluxes at rest, speed).
    git_commit:
        Commit hash of the code that produced the dataset.
    timestamp:
        ISO-8601 creation time.
    output_files:
        Sequence of files written for this dataset.
    run_config:
        Optional reference linking this manifest to the run config that
        produced it. When present it carries at least ``path`` and the
        deterministic ``hash`` of that run config (see
        :mod:`imcm.reporting.run_config`).
    """

    dataset_label: str
    parameter_hash: str
    parameter_source: str
    solver_settings: Mapping[str, Any]
    initial_condition: Mapping[str, Any]
    git_commit: str
    timestamp: str
    output_files: Sequence[str]
    run_config: Union[Mapping[str, Any], None] = None

    # -- validation ---------------------------------------------------------

    def __post_init__(self) -> None:
        self.dataset_label = _validate_dataset_label(self.dataset_label)
        self.parameter_hash = _require_text("parameter_hash", self.parameter_hash)
        self.parameter_source = _require_text(
            "parameter_source", self.parameter_source
        )
        self.solver_settings = _require_mapping(
            "solver_settings", self.solver_settings
        )
        self.initial_condition = _require_mapping(
            "initial_condition", self.initial_condition
        )
        self.git_commit = _require_text("git_commit", self.git_commit)
        self.timestamp = _validate_timestamp(self.timestamp)
        self.output_files = _normalise_output_files(self.output_files)
        if self.run_config is not None:
            self.run_config = _require_mapping("run_config", self.run_config)

    # -- convenience constructors ------------------------------------------

    @classmethod
    def create(
        cls,
        *,
        dataset_label: str,
        parameter_hash: str,
        parameter_source: str,
        solver_settings: Mapping[str, Any],
        initial_condition: Mapping[str, Any],
        git_commit: Union[str, None] = None,
        timestamp: Union[str, None] = None,
        output_files: Iterable[str] = (),
        run_config: Union[Mapping[str, Any], None] = None,
    ) -> "ProvenanceRecord":
        """Build a record, defaulting git commit and timestamp when omitted."""
        return cls(
            dataset_label=dataset_label,
            parameter_hash=parameter_hash,
            parameter_source=parameter_source,
            solver_settings=solver_settings,
            initial_condition=initial_condition,
            git_commit=git_commit if git_commit is not None else detect_git_commit(),
            timestamp=timestamp if timestamp is not None else utc_now_iso(),
            output_files=output_files,
            run_config=run_config,
        )

    # -- serialisation ------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-safe plain-dict representation."""
        payload: dict[str, Any] = {
            "dataset_label": self.dataset_label,
            "parameter_hash": self.parameter_hash,
            "parameter_source": self.parameter_source,
            "solver_settings": _jsonable(self.solver_settings),
            "initial_condition": _jsonable(self.initial_condition),
            "git_commit": self.git_commit,
            "timestamp": self.timestamp,
            "output_files": list(self.output_files),
        }
        if self.run_config is not None:
            payload["run_config"] = _jsonable(self.run_config)
        return payload

    def to_json(self, *, indent: int = 2) -> str:
        """Serialise the record to a JSON string."""
        return json.dumps(self.to_dict(), indent=indent, sort_keys=True)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "ProvenanceRecord":
        """Reconstruct a record from a mapping, enforcing required fields."""
        if not isinstance(data, Mapping):
            raise ProvenanceError(
                "provenance data must be a mapping, "
                f"got {type(data).__name__}"
            )
        missing = [name for name in _REQUIRED_FIELDS if name not in data]
        if missing:
            raise ProvenanceError(
                f"provenance data is missing required fields: {missing}"
            )
        accepted = _REQUIRED_FIELDS + _OPTIONAL_FIELDS
        return cls(**{name: data[name] for name in accepted if name in data})

    @classmethod
    def from_json(cls, text: str) -> "ProvenanceRecord":
        """Parse a record from a JSON string."""
        if not isinstance(text, str):
            raise ProvenanceError(
                f"from_json expects a string, got {type(text).__name__}"
            )
        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            raise ProvenanceError(f"invalid provenance JSON: {exc}") from exc
        if not isinstance(data, Mapping):
            raise ProvenanceError("provenance JSON must decode to an object")
        return cls.from_dict(data)

    # -- reporting ----------------------------------------------------------

    def summary(self) -> str:
        """A short human-readable one-liner for logs and report headers."""
        return (
            f"[{self.dataset_label}] param_hash={self.parameter_hash} "
            f"source={self.parameter_source!r} commit={self.git_commit} "
            f"generated_at={self.timestamp} files={len(self.output_files)}"
        )


# ---------------------------------------------------------------------------
# Manifest I/O
# ---------------------------------------------------------------------------


def write_manifest(
    path: Union[str, Path], record: Union[ProvenanceRecord, Mapping[str, Any]]
) -> Path:
    """Write a provenance record to ``path`` as pretty-printed JSON.

    Parameters
    ----------
    path:
        Destination file. Parent directories are created if needed.
    record:
        A :class:`ProvenanceRecord` or a mapping that can be turned into one.

    Returns
    -------
    pathlib.Path
        The path that was written.
    """
    resolved = _coerce_record(record)
    target = Path(path)
    parent = target.parent
    if parent and not parent.exists():
        parent.mkdir(parents=True, exist_ok=True)
    target.write_text(resolved.to_json() + "\n", encoding="utf-8")
    return target


def read_manifest(path: Union[str, Path]) -> ProvenanceRecord:
    """Read a provenance record previously written by :func:`write_manifest`."""
    text = Path(path).read_text(encoding="utf-8")
    return ProvenanceRecord.from_json(text)